install.packages("devtools")
install_github("SantanderMetGroup/loadeR")
install_github("SantanderMetGroup/transformeR")
install_github("SantanderMetGroup/downscaleR")
install_github("SantanderMetGroup/visualizeR")
